### PR TITLE
[RFR] Revisited the project structure

### PR DESCRIPTION
**Pull request by KittyGiraudel**
This pull-request revisits the project structure to have one entry per file rather than everything in the README. The latter becomes a table of contents. 

It might looks overkill, but I truly think that the README will soon become unpractical and very crowded as we keeping adding more.

Also, having one entry per file leaves some extra room for small projects that we would not have listed in the README otherwise.

Last but not least, it allows us to write more on each entry, without risking of crowding everything.

Any opinion?

### CODE REVIEW

**Comment by gnclmorais** [comment]
That’s an excellent idea, Hugo.

**Comment by elrumordelaluz** [comment]
:+1:

**Comment by codeheroics** [comment]
The separate files look good, but how about keeping a one-line excerpt for each entry (like [awesome-javascript](https://github.com/sorrycc/awesome-javascript) does) in the README.md? That way people can get a quick understanding of what's behind a name without having to leave the main page.

The main README.md is the first (and often the only) thing people see on a Github project, so it'd be cool if it still communicates a bit of simplified jargon!

**Comment by KittyGiraudel** [comment]
> The separate files look good, but how about keeping a one-line excerpt for each entry (like awesome-javascript does) in the README.md? That way people can get a quick understanding of what's behind a name without having to leave the main page.

Very cool idea. We just have to make sure it doesn’t get too long?

**Comment by cahnory** [comment]
Must fit in a tweet? ^^

**Comment by KittyGiraudel** [comment]
> Must fit in a tweet? ^^

I like that.

**Comment by KittyGiraudel** [comment]
Added short description to all entries in README. All good? :)

**Comment by codeheroics** [comment]
Looks good ! =)

**Pull request merged**
