### PR TITLE
[RFR] Added the chrome extension url to README file

### PR DESCRIPTION
**Pull request by ismnoiet**
Add the url of a chrome extension created specifically for same purpose of SJSJ.
A chrome extension with an easy and simple to use interface.

### CODE REVIEW

**Comment by KittyGiraudel** [comment]
Very nice, thanks for doing that. :)

Would be nice to see it on the Chrome Extension Store.

**Comment by ismnoiet** [comment]
Thank you @HugoGiraudel i'll add it to the  chrome store as soon as i solve the problem with my chrome developer account.

**Comment by KittyGiraudel** [comment]
Cool.

Another idea for your extension: when opening a new tab, display a SJSJ entry randomly.

**Comment by ismnoiet** [comment]
+1 Awesome
 I have some cool ideas also that i'll be adding soon.

**Comment by KittyGiraudel** [comment]
For the record, there is now a Node.js script inside the repository to export all the entries as JSON: https://github.com/HugoGiraudel/SJSJ#export-entries-as-json.

**Comment by ismnoiet** [comment]
hhh, this was my next question, thank you.
By the way, i've used a simple php script to generate the json output.

**Pull request merged**
