### PR TITLE
[RFR] Updated “Prototype” entry

### PR DESCRIPTION
**Pull request by virtyaluk**

### CODE REVIEW

**Comment by KittyGiraudel** [comment]
Hey Bohdan! Thank you for your contribution, great as always!

Damn, there was a misunderstanding on this one. When I added the Prototype entry, I was referring to the prototype chain in JavaScript. Something like this: http://javascriptissexy.com/javascript-prototype-in-plain-detailed-language/.

Maybe we can keep this one and rename its file into `PROTOTYPEJS.md`, the entry name into “Prototype.js" and have another entry for the actual JS prototypes? What do you think?

**Comment by virtyaluk** [comment]
@HugoGiraudel 

Ouch, I knew it.

I was pretty sure that it refers to JS prototyping system, but a little later I've started to working on the "Prototype Pattern" entry and I've combined some design patterns concepts and prototyping concept for that entry. So, I've referred to the Prototype library in the "Prototype' entry.

In this case, I'm going to rename it as you wish, and later I'm going to add some article about JS prototyping model.

**Comment by virtyaluk** [comment]
I also think it would be better to name the new entry as `Object Prototypes` since `Prototype` is confusing and may refer to different things.

**Comment by KittyGiraudel** [comment]
Alright, thanks. :)

**Pull request merged**
