### PR TITLE
[RFR] Jekyll version

### PR DESCRIPTION
**Pull request by KittyGiraudel**
This pull-request started from #145. On top:
- Moved the setup to Jekyll;
- No JavaScript dependency for the letter-navigation;
- Usage of datalist + tiny JS snippet for search rather than full blown engine;
- No need for Bootstrap;
- No need for Horsey;
- Fixed all the links to make them work both on GitHub and the site itself (fuck yes).

@kostasx: Do you care to review? :)

### CODE REVIEW

**Comment by kostasx** [comment]
Los geht's!

**Comment by KittyGiraudel** [comment]
Do you think it's good enough to be merged safely? :)

**Comment by kostasx** [comment]
To tell you the truth, I haven't had any experience with Jekyll so far.
But why not give it a shot?

**Comment by KittyGiraudel** [comment]
Sure. Why not. :)

**Pull request merged**
