### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AshCoolman**
some to get you started

### CODE REVIEW

**Comment by KittyGiraudel** [comment]
Hey! Some of it has been done already, so allow me to extract them as separate PR. :)

**Comment by KittyGiraudel** [comment]
Merged through:
- #20
- #21
- #22
- https://github.com/HugoGiraudel/SJSJ/commit/d29f6e8e8de7e4552946e0f9a17ee8ab5ea9ffa6
- https://github.com/HugoGiraudel/SJSJ/commit/9e502d74a659480d1a1dc176b5c85eb40dbef2ea

While I do appreciate the extensive explanation about Angular2, I am wondering whether it is worth mentioning it. People are likely to ask themselves about what is Angular, and knowing about the new controller architecture of Angular2 might fall out of scope. What do you think?

**Comment by AshCoolman** [comment]
Hm, yeah I understand now - this is a "first point of reference" document, so any comparison _is_ out of the scope. :+1:

**Comment by KittyGiraudel** [comment]
Great, thanks!

**Pull request closed without merging**
