### PR TITLE
[RFR] Added “AJAX” entry

### PR DESCRIPTION
**Pull request by rachitGulati**

### CODE REVIEW

**Comment by KittyGiraudel** [comment]
Thanks! :)

**Comment by rachitGulati** [comment]
Please roll back it.
I mistakenly remove the enter from one line.

**Comment by KittyGiraudel** [comment]
All good: https://github.com/HugoGiraudel/SJSJ/commit/b2b153ee5b8c4531e93035b78d506a9bc3efa42b. :)

**Comment by rachitGulati** [comment]
Yeah I reset commit from my local and pushed it again :).

**Pull request merged**
