### PR TITLE
[RFR] Added “Design Patterns” entry and logo proposal

### PR DESCRIPTION
**Pull request by kostasx**
Adding Design Patterns and several example design pattern enties (sections to be completed) and a logo suggestion on the images folder.

### CODE REVIEW

**Comment by KittyGiraudel** [comment]
Merged! I’ll tackle the logo soon.

**Comment by kostasx** [comment]
Sorry about including both the logo and the Design Patterns in the same Pull Request. I've messed up with the repo, and had to recreate it. Feel free to use the logo images as you please.

**Comment by KittyGiraudel** [comment]
The logo is live and looking great. Thanks a lot! :)

**Comment by KittyGiraudel** [comment]
@kostasx Did you by any chance created a favicon with the logo? :)

**Comment by kostasx** [comment]
@HugoGiraudel Just pushed.

**Pull request merged**
