### PR TITLE
[WIP] Added several entries

### PR DESCRIPTION
**Pull request by mallowigi**
Add MongoDB, Modernizr, currying, lodash, zepto, sass, q

### CODE REVIEW

**Comment by KittyGiraudel** [comment]
Sass should not be part of this list. Also, I will only merge when the entries are being written. I'll leave this open in the meantime. :)

**Comment by mallowigi** [comment]
Here

**Comment by mallowigi** [comment]
bump

**Comment by KittyGiraudel** [comment]
Hey! Thanks for bumping this thread as I didn’t see you added the entries. I will take care of this today for sure. Thank you! :)

**Pull request merged**
